// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package com.moGrpc.gRpc;

public interface APIResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:APIResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string responseCode = 1;</code>
   * @return The responseCode.
   */
  java.lang.String getResponseCode();
  /**
   * <code>string responseCode = 1;</code>
   * @return The bytes for responseCode.
   */
  com.google.protobuf.ByteString
      getResponseCodeBytes();

  /**
   * <code>string Status = 2;</code>
   * @return The status.
   */
  java.lang.String getStatus();
  /**
   * <code>string Status = 2;</code>
   * @return The bytes for status.
   */
  com.google.protobuf.ByteString
      getStatusBytes();
}
