// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package com.moGrpc.gRpc;

/**
 * Protobuf service {@code User}
 */
public  abstract class User
    implements com.google.protobuf.Service {
  protected User() {}

  public interface Interface {
    /**
     * <code>rpc login(.loginRequest) returns (.APIResponse);</code>
     */
    public abstract void login(
        com.google.protobuf.RpcController controller,
        com.moGrpc.gRpc.loginRequest request,
        com.google.protobuf.RpcCallback<com.moGrpc.gRpc.APIResponse> done);

  }

  public static com.google.protobuf.Service newReflectiveService(
      final Interface impl) {
    return new User() {
      @java.lang.Override
      public  void login(
          com.google.protobuf.RpcController controller,
          com.moGrpc.gRpc.loginRequest request,
          com.google.protobuf.RpcCallback<com.moGrpc.gRpc.APIResponse> done) {
        impl.login(controller, request, done);
      }

    };
  }

  public static com.google.protobuf.BlockingService
      newReflectiveBlockingService(final BlockingInterface impl) {
    return new com.google.protobuf.BlockingService() {
      public final com.google.protobuf.Descriptors.ServiceDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }

      public final com.google.protobuf.Message callBlockingMethod(
          com.google.protobuf.Descriptors.MethodDescriptor method,
          com.google.protobuf.RpcController controller,
          com.google.protobuf.Message request)
          throws com.google.protobuf.ServiceException {
        if (method.getService() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "Service.callBlockingMethod() given method descriptor for " +
            "wrong service type.");
        }
        switch(method.getIndex()) {
          case 0:
            return impl.login(controller, (com.moGrpc.gRpc.loginRequest)request);
          default:
            throw new java.lang.AssertionError("Can't get here.");
        }
      }

      public final com.google.protobuf.Message
          getRequestPrototype(
          com.google.protobuf.Descriptors.MethodDescriptor method) {
        if (method.getService() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "Service.getRequestPrototype() given method " +
            "descriptor for wrong service type.");
        }
        switch(method.getIndex()) {
          case 0:
            return com.moGrpc.gRpc.loginRequest.getDefaultInstance();
          default:
            throw new java.lang.AssertionError("Can't get here.");
        }
      }

      public final com.google.protobuf.Message
          getResponsePrototype(
          com.google.protobuf.Descriptors.MethodDescriptor method) {
        if (method.getService() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "Service.getResponsePrototype() given method " +
            "descriptor for wrong service type.");
        }
        switch(method.getIndex()) {
          case 0:
            return com.moGrpc.gRpc.APIResponse.getDefaultInstance();
          default:
            throw new java.lang.AssertionError("Can't get here.");
        }
      }

    };
  }

  /**
   * <code>rpc login(.loginRequest) returns (.APIResponse);</code>
   */
  public abstract void login(
      com.google.protobuf.RpcController controller,
      com.moGrpc.gRpc.loginRequest request,
      com.google.protobuf.RpcCallback<com.moGrpc.gRpc.APIResponse> done);

  public static final
      com.google.protobuf.Descriptors.ServiceDescriptor
      getDescriptor() {
    return com.moGrpc.gRpc.UserOuterClass.getDescriptor().getServices().get(0);
  }
  public final com.google.protobuf.Descriptors.ServiceDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }

  public final void callMethod(
      com.google.protobuf.Descriptors.MethodDescriptor method,
      com.google.protobuf.RpcController controller,
      com.google.protobuf.Message request,
      com.google.protobuf.RpcCallback<
        com.google.protobuf.Message> done) {
    if (method.getService() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "Service.callMethod() given method descriptor for wrong " +
        "service type.");
    }
    switch(method.getIndex()) {
      case 0:
        this.login(controller, (com.moGrpc.gRpc.loginRequest)request,
          com.google.protobuf.RpcUtil.<com.moGrpc.gRpc.APIResponse>specializeCallback(
            done));
        return;
      default:
        throw new java.lang.AssertionError("Can't get here.");
    }
  }

  public final com.google.protobuf.Message
      getRequestPrototype(
      com.google.protobuf.Descriptors.MethodDescriptor method) {
    if (method.getService() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "Service.getRequestPrototype() given method " +
        "descriptor for wrong service type.");
    }
    switch(method.getIndex()) {
      case 0:
        return com.moGrpc.gRpc.loginRequest.getDefaultInstance();
      default:
        throw new java.lang.AssertionError("Can't get here.");
    }
  }

  public final com.google.protobuf.Message
      getResponsePrototype(
      com.google.protobuf.Descriptors.MethodDescriptor method) {
    if (method.getService() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "Service.getResponsePrototype() given method " +
        "descriptor for wrong service type.");
    }
    switch(method.getIndex()) {
      case 0:
        return com.moGrpc.gRpc.APIResponse.getDefaultInstance();
      default:
        throw new java.lang.AssertionError("Can't get here.");
    }
  }

  public static Stub newStub(
      com.google.protobuf.RpcChannel channel) {
    return new Stub(channel);
  }

  public static final class Stub extends com.moGrpc.gRpc.UserService.UserService implements Interface {
    private Stub(com.google.protobuf.RpcChannel channel) {
      this.channel = channel;
    }

    private final com.google.protobuf.RpcChannel channel;

    public com.google.protobuf.RpcChannel getChannel() {
      return channel;
    }

    public  void login(
        com.google.protobuf.RpcController controller,
        com.moGrpc.gRpc.loginRequest request,
        com.google.protobuf.RpcCallback<com.moGrpc.gRpc.APIResponse> done) {
      channel.callMethod(
        getDescriptor().getMethods().get(0),
        controller,
        request,
        com.moGrpc.gRpc.APIResponse.getDefaultInstance(),
        com.google.protobuf.RpcUtil.generalizeCallback(
          done,
          com.moGrpc.gRpc.APIResponse.class,
          com.moGrpc.gRpc.APIResponse.getDefaultInstance()));
    }
  }

  public static BlockingInterface newBlockingStub(
      com.google.protobuf.BlockingRpcChannel channel) {
    return new BlockingStub(channel);
  }

  public interface BlockingInterface {
    public com.moGrpc.gRpc.APIResponse login(
        com.google.protobuf.RpcController controller,
        com.moGrpc.gRpc.loginRequest request)
        throws com.google.protobuf.ServiceException;
  }

  private static final class BlockingStub implements BlockingInterface {
    private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
      this.channel = channel;
    }

    private final com.google.protobuf.BlockingRpcChannel channel;

    public com.moGrpc.gRpc.APIResponse login(
        com.google.protobuf.RpcController controller,
        com.moGrpc.gRpc.loginRequest request)
        throws com.google.protobuf.ServiceException {
      return (com.moGrpc.gRpc.APIResponse) channel.callBlockingMethod(
        getDescriptor().getMethods().get(0),
        controller,
        request,
        com.moGrpc.gRpc.APIResponse.getDefaultInstance());
    }

  }

  // @@protoc_insertion_point(class_scope:User)
}

